name: Run Training Pipeline

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - continuous-training

permissions:
  id-token: write
  contents: read

jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint code
        run: echo "Linting repository"

      - name: Run unit tests
        run: echo "Running unit tests"

  training:
    name: Continuous Training
    runs-on: ubuntu-latest
    needs: delivery
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install kfp requirements
        run: |
          pip3 install -r requirements.txt

      - name: Run kfp training pipeline
        env:
          KUBEFLOW_ENDPOINT: ${{ secrets.KUBEFLOW_ENDPOINT }}
          KUBEFLOW_USERNAME: ${{ secrets.KUBEFLOW_USERNAME }}
          KUBEFLOW_PASSWORD: ${{ secrets.KUBEFLOW_PASSWORD }}
          MONGO_DB_URL: ${{ secrets.MONGO_DB_URL }}
        run: |
          python3 train.py
